from django import forms

from .models import Post

class PostForm(forms.ModelForm):           #PostForm is the name of our form and We need to tell Django that this form is a ModelForm

    class Meta:
        model = Post
        fields = ('title', 'text',)     # In Post model we have author,title,date....but to add post we need only title and text fields author and date are autogenerated